// <auto-generated />
using BloodBankManagementSystem.database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BloodBankManagementSystem.Migrations
{
    [DbContext(typeof(DonorContext))]
    [Migration("20221124124636_initia")]
    partial class initia
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BloodBankManagementSystem.Models.DonorDetails", b =>
                {
                    b.Property<int>("donorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("donorId"), 1L, 1);

                    b.Property<int>("donorAge")
                        .HasColumnType("int");

                    b.Property<string>("donorBloodType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("donorEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("donorMob")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("donorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("donorWeight")
                        .HasColumnType("int");

                    b.Property<int>("donorheight")
                        .HasColumnType("int");

                    b.HasKey("donorId");

                    b.ToTable("DonorDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
